Repository greenbone/ospd-openvas, pull requests merged in 2022-08, with the labels that each got.

#713 Fix notus results
  ospd_openvas/messaging/mqtt.py
  poetry.lock
  pyproject.toml
Labels: backport-to-stable

#728 Fix: unable to restart container after it was killed
  ospd/misc.py
Labels: backport-to-stable

#740 Fix: Improve handling of unknown scan ids
  ospd_openvas/daemon.py
Labels: backport-to-main

#743 Refactor: change name of patch release
  .github/workflows/release-pontos-manually.yml
Labels: backport-to-stable

#745 Use docker meta action
  .docker/prod.Dockerfile
  .dockerignore
  .github/workflows/container.yml
Labels: backport-to-oldstable, backport-to-stable

#748 Change: Build container images for pull requests too
  .github/workflows/container.yml
Labels: backport-to-oldstable, backport-to-stable

#754 Change: Don't use a pip cache within the container build
  .docker/prod.Dockerfile
Labels: backport-to-oldstable, backport-to-stable

#751 Fix: Stop and clean finished/running openvas process before resumming a scan
  ospd_openvas/daemon.py
  ospd_openvas/db.py
Labels: backport-to-stable

#760 Fix: race condition within daemon and notus
  ospd_openvas/daemon.py
  ospd_openvas/notus.py
  tests/test_daemon.py
  tests/test_notus.py
Labels: backport-to-stable
